### ISSUE TITLE
Unable to build on RISC-V

### ISSUE THREAD

**Issue by archanox** [hrydgard/ppsspp-ffmpeg#62]
When attempting to run `./configure` I get the following;

```
root@debian:~/ppsspp/ffmpeg# ./configure
install prefix            /usr/local
source path               .
C compiler                gcc
C library                 glibc
ARCH                      riscv64 (generic)
big-endian                no
runtime cpu detection     yes
debug symbols             yes
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    no
postprocessing support    no
new filter support        yes
network support           yes
threading support         pthreads
safe bitstream reader     yes
SDL support               no
opencl enabled            no
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          no
makeinfo supports HTML    no

Enabled programs:
ffmpeg                  ffprobe

...

License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...
config.h is unchanged
libavutil/avconfig.h is unchanged

WARNING: unknown architecture riscv64
```

**Comment by archanox** [comment]
I've also encountered an issue with the FFmpeg/gas-preprocessor submodule, but i'm unable to create an issue in that repo.

```
root@debian:~/ppsspp/ffmpeg/gas-preprocessor# make
./gas-preprocessor.pl -as-type gas -- arm-linux-gnueabihf-gcc -c test.S -o test.o
Error running preprocessor at ./gas-preprocessor.pl line 210.
make: *** [Makefile:5: test] Error 2
```

**Comment by unknownbrackets** [comment]
This repo really just contains:
 * FFmpeg 3.0.2, without modifications (AFAIK._
 * Build scripts to build a minimal static FFmpeg library for several platforms.
 * Prebuilt binaries of FFmpeg libs for several platforms.

I would guess that gas is failing due to some argument problem:
https://github.com/FFmpeg/gas-preprocessor/blob/cbe88474ec196370161032a3863ec65050f70ba4/gas-preprocessor.pl#L210

If you can otherwise build or install FFmpeg for your platform (even a later version), you may be able to use that.  A few things:
 * You'll want to have ATRAC3+ support, which is optional.
 * There are some compatibility problems with newer FFmpeg; it doesn't always support adding streams dynamically anymore, which some PSP games do/require, but the majority don't.
 * You'll want to use a recent git build of PPSSPP, older will have more problems with newer FFmpeg versions than just the above.

Maybe we could backport a fix to riscv64 compilation, assuming latest FFmpeg does build fine.

-[Unknown]

**Comment by archanox** [comment]
Sorry this took a while to determine, (storage issues) but everything compiles fine on my risc-v qemu image and on actual hardware.

I don't see Gas upstream here https://github.com/FFmpeg/FFmpeg so I'm not sure where the issue was introduced here.

**Comment by archanox** [comment]
Also found here are the results of a successful build for debian https://buildd.debian.org/status/fetch.php?pkg=ffmpeg&arch=riscv64&ver=7%3A4.3.2-0%2Bdeb11u1&stamp=1613973832&raw=0

**Comment by unknownbrackets** [comment]
I think the latest FFmpeg expects you to install gas-preprocessor separately and put it on your path:
https://github.com/FFmpeg/FFmpeg/blob/870bfe16a12bf09dca3a4ae27ef6f81a2de80c40/doc/platform.texi#L68-L72

But it's not actually supposed to be used in the first place for all platforms, i.e. not Intel even.  See here:
https://github.com/hrydgard/ppsspp-ffmpeg/blob/7da319f641b6e094f1987c4491c57a30a13c00f5/configure#L4971

Vs:
https://github.com/FFmpeg/FFmpeg/blob/8bcce5673a267ed371140bf3228ffb420ca2f69b/configure#L5830

Anyway, if that built you can try `-DUSE_SYSTEM_FFMPEG=1` for PPSSPP, using the latest git.  Again, there are some downsides to this but I know a bunch of packagers don't care and do it anyway, so most Linux/macOS builds that aren't self-compiled already are a worse experience than Windows/Android in the affected games for this reason.

Presumably if you tried to compile FFmpeg 3.0.2 (as I've mentioned, an intentionally older version), it wouldn't work.  Perhaps we could try bisecting on the FFmpeg repo to find where they fixed riscv64 compilation.

-[Unknown]

**Comment by archanox** [comment]
For completeness sake, this submodule does build and install, it just throws up the warning that riscv64 is an unsupported architecture.

**Comment by archanox** [comment]
I hacked together a script based on the linux_mips32.sh script for riscv64 which got me over the line to compile this.
[linux_riscv64.sh.txt](https://github.com/hrydgard/ppsspp-ffmpeg/files/6681352/linux_riscv64.sh.txt)
